# Generated by Django 3.2.16 on 2022-12-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_name', models.ForeignKey(blank=True, db_column='project_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.projects')),
                ('user', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'walls',
            },
        ),
    ]
